name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore TestMachina/TestMachina.csproj
      - name: Build
        run: dotnet build TestMachina/TestMachina.csproj --no-restore
      - name: Test
        run: dotnet test TestMachina/TestMachina.csproj --no-build --verbosity normal
